name: hugo build

on:
  pull_request:
    paths:
      - "layouts/**"
      - "assets/**"
      - "static/**"
      - "archetypes/**"
      - "theme.toml"
      - "exampleSite/**"
      - ".github/workflows/hugo-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.150.1"
          extended: true

      - name: Build
        run: hugo --themesDir ../.. --theme simplog --minify
        working-directory: ./exampleSite
