name: tagpr

on:
  push:
    branches:
      - master

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: Songmu/tagpr@e84001bd5dac8defa0c75b3913937d284a3b3660 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
