name: tagpr

on:
  push:
    branches:
      - master

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: Songmu/tagpr@7ebae2dcc300132baa7cc9dd108c8923b07fc366 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
